# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(975, 822)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tableView = QtWidgets.QTableView(self.centralwidget)
        self.tableView.setGeometry(QtCore.QRect(10, 390, 941, 411))
        self.tableView.setObjectName("tableView")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 30, 921, 341))
        self.tabWidget.setObjectName("tabWidget")
        self.tab1 = QtWidgets.QWidget()
        self.tab1.setObjectName("tab1")
        self.frame = QtWidgets.QFrame(self.tab1)
        self.frame.setGeometry(QtCore.QRect(10, 20, 901, 261))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.layoutWidget = QtWidgets.QWidget(self.frame)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 20, 183, 61))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_56 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_56.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_56.setObjectName("verticalLayout_56")
        self.label_69 = QtWidgets.QLabel(self.layoutWidget)
        self.label_69.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("candara")
        font.setPointSize(10)
        self.label_69.setFont(font)
        self.label_69.setStyleSheet("color:#838383;")
        self.label_69.setObjectName("label_69")
        self.verticalLayout_56.addWidget(self.label_69)
        self.horizontalLayout_37 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_37.setSpacing(0)
        self.horizontalLayout_37.setObjectName("horizontalLayout_37")
        self.txtReportStartDate = QtWidgets.QLineEdit(self.layoutWidget)
        self.txtReportStartDate.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("candara")
        font.setPointSize(11)
        self.txtReportStartDate.setFont(font)
        self.txtReportStartDate.setStyleSheet("background-color:#D9D9D9;\n"
"border:none;")
        self.txtReportStartDate.setText("")
        self.txtReportStartDate.setObjectName("txtReportStartDate")
        self.horizontalLayout_37.addWidget(self.txtReportStartDate)
        self.btnGetReportStartDate = QtWidgets.QPushButton(self.layoutWidget)
        self.btnGetReportStartDate.setMinimumSize(QtCore.QSize(0, 30))
        self.btnGetReportStartDate.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setFamily("candara")
        font.setPointSize(10)
        self.btnGetReportStartDate.setFont(font)
        self.btnGetReportStartDate.setStyleSheet("QPushButton{\n"
"background-color:#2F8FEA;\n"
"border:none;\n"
"color: white;\n"
"text-align: center;\n"
"padding: 0px 15px;\n"
"border-radius:0;\n"
"\n"
"}\n"
"QPushButton:hover{\n"
"    background-color:#007DDA;\n"
"    background-color: #56648F;\n"
"    \n"
"}")
        self.btnGetReportStartDate.setObjectName("btnGetReportStartDate")
        self.horizontalLayout_37.addWidget(self.btnGetReportStartDate)
        self.verticalLayout_56.addLayout(self.horizontalLayout_37)
        self.layoutWidget_2 = QtWidgets.QWidget(self.frame)
        self.layoutWidget_2.setGeometry(QtCore.QRect(210, 20, 183, 61))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.verticalLayout_57 = QtWidgets.QVBoxLayout(self.layoutWidget_2)
        self.verticalLayout_57.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_57.setObjectName("verticalLayout_57")
        self.label_70 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_70.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("candara")
        font.setPointSize(10)
        self.label_70.setFont(font)
        self.label_70.setStyleSheet("color:#838383;")
        self.label_70.setObjectName("label_70")
        self.verticalLayout_57.addWidget(self.label_70)
        self.horizontalLayout_38 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_38.setSpacing(0)
        self.horizontalLayout_38.setObjectName("horizontalLayout_38")
        self.txtReportStartDate_2 = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.txtReportStartDate_2.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("candara")
        font.setPointSize(11)
        self.txtReportStartDate_2.setFont(font)
        self.txtReportStartDate_2.setStyleSheet("background-color:#D9D9D9;\n"
"border:none;")
        self.txtReportStartDate_2.setText("")
        self.txtReportStartDate_2.setObjectName("txtReportStartDate_2")
        self.horizontalLayout_38.addWidget(self.txtReportStartDate_2)
        self.btnGetReportStartDate_2 = QtWidgets.QPushButton(self.layoutWidget_2)
        self.btnGetReportStartDate_2.setMinimumSize(QtCore.QSize(0, 30))
        self.btnGetReportStartDate_2.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setFamily("candara")
        font.setPointSize(10)
        self.btnGetReportStartDate_2.setFont(font)
        self.btnGetReportStartDate_2.setStyleSheet("QPushButton{\n"
"background-color:#2F8FEA;\n"
"border:none;\n"
"color: white;\n"
"text-align: center;\n"
"padding: 0px 15px;\n"
"border-radius:0;\n"
"\n"
"}\n"
"QPushButton:hover{\n"
"    background-color:#007DDA;\n"
"    background-color: #56648F;\n"
"    \n"
"}")
        self.btnGetReportStartDate_2.setObjectName("btnGetReportStartDate_2")
        self.horizontalLayout_38.addWidget(self.btnGetReportStartDate_2)
        self.verticalLayout_57.addLayout(self.horizontalLayout_38)
        self.layoutWidget_3 = QtWidgets.QWidget(self.frame)
        self.layoutWidget_3.setGeometry(QtCore.QRect(400, 20, 161, 59))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.verticalLayout_58 = QtWidgets.QVBoxLayout(self.layoutWidget_3)
        self.verticalLayout_58.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_58.setObjectName("verticalLayout_58")
        self.label_71 = QtWidgets.QLabel(self.layoutWidget_3)
        self.label_71.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("candara")
        font.setPointSize(10)
        self.label_71.setFont(font)
        self.label_71.setStyleSheet("color:#838383;")
        self.label_71.setObjectName("label_71")
        self.verticalLayout_58.addWidget(self.label_71)
        self.cmbReportRecordType = QtWidgets.QComboBox(self.layoutWidget_3)
        self.cmbReportRecordType.setMinimumSize(QtCore.QSize(0, 30))
        self.cmbReportRecordType.setStyleSheet("border:none;\n"
"background-color:#D9D9D9;")
        self.cmbReportRecordType.setEditable(True)
        self.cmbReportRecordType.setObjectName("cmbReportRecordType")
        self.verticalLayout_58.addWidget(self.cmbReportRecordType)
        self.layoutWidget_4 = QtWidgets.QWidget(self.frame)
        self.layoutWidget_4.setGeometry(QtCore.QRect(570, 20, 181, 53))
        self.layoutWidget_4.setObjectName("layoutWidget_4")
        self.verticalLayout_24 = QtWidgets.QVBoxLayout(self.layoutWidget_4)
        self.verticalLayout_24.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_24.setObjectName("verticalLayout_24")
        self.label_31 = QtWidgets.QLabel(self.layoutWidget_4)
        self.label_31.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("candara")
        font.setPointSize(10)
        self.label_31.setFont(font)
        self.label_31.setStyleSheet("color:#838383;")
        self.label_31.setObjectName("label_31")
        self.verticalLayout_24.addWidget(self.label_31)
        self.txtIncomeRecordedBy = QtWidgets.QLineEdit(self.layoutWidget_4)
        self.txtIncomeRecordedBy.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("candara")
        font.setPointSize(11)
        self.txtIncomeRecordedBy.setFont(font)
        self.txtIncomeRecordedBy.setStyleSheet("background-color:#D9D9D9;\n"
"border:none;")
        self.txtIncomeRecordedBy.setText("")
        self.txtIncomeRecordedBy.setObjectName("txtIncomeRecordedBy")
        self.verticalLayout_24.addWidget(self.txtIncomeRecordedBy)
        self.layoutWidget_5 = QtWidgets.QWidget(self.frame)
        self.layoutWidget_5.setGeometry(QtCore.QRect(20, 90, 181, 53))
        self.layoutWidget_5.setObjectName("layoutWidget_5")
        self.verticalLayout_25 = QtWidgets.QVBoxLayout(self.layoutWidget_5)
        self.verticalLayout_25.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_25.setObjectName("verticalLayout_25")
        self.label_32 = QtWidgets.QLabel(self.layoutWidget_5)
        self.label_32.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("candara")
        font.setPointSize(10)
        self.label_32.setFont(font)
        self.label_32.setStyleSheet("color:#838383;")
        self.label_32.setObjectName("label_32")
        self.verticalLayout_25.addWidget(self.label_32)
        self.txtIncomeRecordedBy_2 = QtWidgets.QLineEdit(self.layoutWidget_5)
        self.txtIncomeRecordedBy_2.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("candara")
        font.setPointSize(11)
        self.txtIncomeRecordedBy_2.setFont(font)
        self.txtIncomeRecordedBy_2.setStyleSheet("background-color:#D9D9D9;\n"
"border:none;")
        self.txtIncomeRecordedBy_2.setText("")
        self.txtIncomeRecordedBy_2.setObjectName("txtIncomeRecordedBy_2")
        self.verticalLayout_25.addWidget(self.txtIncomeRecordedBy_2)
        self.layoutWidget_6 = QtWidgets.QWidget(self.frame)
        self.layoutWidget_6.setGeometry(QtCore.QRect(20, 150, 371, 92))
        self.layoutWidget_6.setObjectName("layoutWidget_6")
        self.verticalLayout_26 = QtWidgets.QVBoxLayout(self.layoutWidget_6)
        self.verticalLayout_26.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_26.setObjectName("verticalLayout_26")
        self.label_33 = QtWidgets.QLabel(self.layoutWidget_6)
        self.label_33.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("candara")
        font.setPointSize(10)
        self.label_33.setFont(font)
        self.label_33.setStyleSheet("color:#838383;")
        self.label_33.setObjectName("label_33")
        self.verticalLayout_26.addWidget(self.label_33)
        self.textEdit = QtWidgets.QTextEdit(self.layoutWidget_6)
        self.textEdit.setStyleSheet("background-color:#D9D9D9;\n"
"border:none;")
        self.textEdit.setObjectName("textEdit")
        self.verticalLayout_26.addWidget(self.textEdit)
        self.layoutWidget_7 = QtWidgets.QWidget(self.frame)
        self.layoutWidget_7.setGeometry(QtCore.QRect(400, 90, 161, 53))
        self.layoutWidget_7.setObjectName("layoutWidget_7")
        self.verticalLayout_27 = QtWidgets.QVBoxLayout(self.layoutWidget_7)
        self.verticalLayout_27.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_27.setObjectName("verticalLayout_27")
        self.label_34 = QtWidgets.QLabel(self.layoutWidget_7)
        self.label_34.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("candara")
        font.setPointSize(10)
        self.label_34.setFont(font)
        self.label_34.setStyleSheet("color:#838383;")
        self.label_34.setObjectName("label_34")
        self.verticalLayout_27.addWidget(self.label_34)
        self.txtIncomeRecordedBy_4 = QtWidgets.QLineEdit(self.layoutWidget_7)
        self.txtIncomeRecordedBy_4.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("candara")
        font.setPointSize(11)
        self.txtIncomeRecordedBy_4.setFont(font)
        self.txtIncomeRecordedBy_4.setStyleSheet("background-color:#D9D9D9;\n"
"border:none;")
        self.txtIncomeRecordedBy_4.setText("")
        self.txtIncomeRecordedBy_4.setObjectName("txtIncomeRecordedBy_4")
        self.verticalLayout_27.addWidget(self.txtIncomeRecordedBy_4)
        self.layoutWidget_8 = QtWidgets.QWidget(self.frame)
        self.layoutWidget_8.setGeometry(QtCore.QRect(210, 90, 181, 53))
        self.layoutWidget_8.setObjectName("layoutWidget_8")
        self.verticalLayout_28 = QtWidgets.QVBoxLayout(self.layoutWidget_8)
        self.verticalLayout_28.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_28.setObjectName("verticalLayout_28")
        self.label_35 = QtWidgets.QLabel(self.layoutWidget_8)
        self.label_35.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("candara")
        font.setPointSize(10)
        self.label_35.setFont(font)
        self.label_35.setStyleSheet("color:#838383;")
        self.label_35.setObjectName("label_35")
        self.verticalLayout_28.addWidget(self.label_35)
        self.txtIncomeRecordedBy_5 = QtWidgets.QLineEdit(self.layoutWidget_8)
        self.txtIncomeRecordedBy_5.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("candara")
        font.setPointSize(11)
        self.txtIncomeRecordedBy_5.setFont(font)
        self.txtIncomeRecordedBy_5.setStyleSheet("background-color:#D9D9D9;\n"
"border:none;")
        self.txtIncomeRecordedBy_5.setText("")
        self.txtIncomeRecordedBy_5.setObjectName("txtIncomeRecordedBy_5")
        self.verticalLayout_28.addWidget(self.txtIncomeRecordedBy_5)
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setGeometry(QtCore.QRect(400, 150, 461, 101))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.btnGetCurrentStock = QtWidgets.QPushButton(self.frame_2)
        self.btnGetCurrentStock.setGeometry(QtCore.QRect(10, 40, 121, 40))
        self.btnGetCurrentStock.setMinimumSize(QtCore.QSize(0, 40))
        self.btnGetCurrentStock.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setFamily("candara")
        font.setPointSize(10)
        self.btnGetCurrentStock.setFont(font)
        self.btnGetCurrentStock.setStyleSheet("QPushButton{\n"
"background-color:#487A85;\n"
"border:none;\n"
"color: white;\n"
"text-align: center;\n"
"padding: 0px 15px;\n"
"border-radius:10px;\n"
"\n"
"}\n"
"QPushButton:hover{\n"
"    background-color:#007DDA;\n"
"    background-color: #56648F;\n"
"    \n"
"}")
        self.btnGetCurrentStock.setObjectName("btnGetCurrentStock")
        self.btnGetCurrentStock_2 = QtWidgets.QPushButton(self.frame_2)
        self.btnGetCurrentStock_2.setGeometry(QtCore.QRect(140, 40, 121, 40))
        self.btnGetCurrentStock_2.setMinimumSize(QtCore.QSize(0, 40))
        self.btnGetCurrentStock_2.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setFamily("candara")
        font.setPointSize(10)
        self.btnGetCurrentStock_2.setFont(font)
        self.btnGetCurrentStock_2.setStyleSheet("QPushButton{\n"
"background-color:#487A85;\n"
"border:none;\n"
"color: white;\n"
"text-align: center;\n"
"padding: 0px 15px;\n"
"border-radius:10px;\n"
"\n"
"}\n"
"QPushButton:hover{\n"
"    background-color:#007DDA;\n"
"    background-color: #56648F;\n"
"    \n"
"}")
        self.btnGetCurrentStock_2.setObjectName("btnGetCurrentStock_2")
        self.btnGetCurrentStock_3 = QtWidgets.QPushButton(self.frame_2)
        self.btnGetCurrentStock_3.setGeometry(QtCore.QRect(280, 40, 121, 40))
        self.btnGetCurrentStock_3.setMinimumSize(QtCore.QSize(0, 40))
        self.btnGetCurrentStock_3.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setFamily("candara")
        font.setPointSize(10)
        self.btnGetCurrentStock_3.setFont(font)
        self.btnGetCurrentStock_3.setStyleSheet("QPushButton{\n"
"background-color:#487A85;\n"
"border:none;\n"
"color: white;\n"
"text-align: center;\n"
"padding: 0px 15px;\n"
"border-radius:10px;\n"
"\n"
"}\n"
"QPushButton:hover{\n"
"    background-color:#007DDA;\n"
"    background-color: #56648F;\n"
"    \n"
"}")
        self.btnGetCurrentStock_3.setObjectName("btnGetCurrentStock_3")
        self.tabWidget.addTab(self.tab1, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.frame_3 = QtWidgets.QFrame(self.tab_2)
        self.frame_3.setGeometry(QtCore.QRect(10, 10, 901, 261))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.layoutWidget_9 = QtWidgets.QWidget(self.frame_3)
        self.layoutWidget_9.setGeometry(QtCore.QRect(20, 20, 183, 61))
        self.layoutWidget_9.setObjectName("layoutWidget_9")
        self.verticalLayout_59 = QtWidgets.QVBoxLayout(self.layoutWidget_9)
        self.verticalLayout_59.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_59.setObjectName("verticalLayout_59")
        self.label_72 = QtWidgets.QLabel(self.layoutWidget_9)
        self.label_72.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("candara")
        font.setPointSize(10)
        self.label_72.setFont(font)
        self.label_72.setStyleSheet("color:#838383;")
        self.label_72.setObjectName("label_72")
        self.verticalLayout_59.addWidget(self.label_72)
        self.horizontalLayout_39 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_39.setSpacing(0)
        self.horizontalLayout_39.setObjectName("horizontalLayout_39")
        self.txtReportStartDate_3 = QtWidgets.QLineEdit(self.layoutWidget_9)
        self.txtReportStartDate_3.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("candara")
        font.setPointSize(11)
        self.txtReportStartDate_3.setFont(font)
        self.txtReportStartDate_3.setStyleSheet("background-color:#D9D9D9;\n"
"border:none;")
        self.txtReportStartDate_3.setText("")
        self.txtReportStartDate_3.setObjectName("txtReportStartDate_3")
        self.horizontalLayout_39.addWidget(self.txtReportStartDate_3)
        self.btnGetReportStartDate_3 = QtWidgets.QPushButton(self.layoutWidget_9)
        self.btnGetReportStartDate_3.setMinimumSize(QtCore.QSize(0, 30))
        self.btnGetReportStartDate_3.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setFamily("candara")
        font.setPointSize(10)
        self.btnGetReportStartDate_3.setFont(font)
        self.btnGetReportStartDate_3.setStyleSheet("QPushButton{\n"
"background-color:#2F8FEA;\n"
"border:none;\n"
"color: white;\n"
"text-align: center;\n"
"padding: 0px 15px;\n"
"border-radius:0;\n"
"\n"
"}\n"
"QPushButton:hover{\n"
"    background-color:#007DDA;\n"
"    background-color: #56648F;\n"
"    \n"
"}")
        self.btnGetReportStartDate_3.setObjectName("btnGetReportStartDate_3")
        self.horizontalLayout_39.addWidget(self.btnGetReportStartDate_3)
        self.verticalLayout_59.addLayout(self.horizontalLayout_39)
        self.layoutWidget_10 = QtWidgets.QWidget(self.frame_3)
        self.layoutWidget_10.setGeometry(QtCore.QRect(210, 20, 183, 61))
        self.layoutWidget_10.setObjectName("layoutWidget_10")
        self.verticalLayout_60 = QtWidgets.QVBoxLayout(self.layoutWidget_10)
        self.verticalLayout_60.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_60.setObjectName("verticalLayout_60")
        self.label_73 = QtWidgets.QLabel(self.layoutWidget_10)
        self.label_73.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("candara")
        font.setPointSize(10)
        self.label_73.setFont(font)
        self.label_73.setStyleSheet("color:#838383;")
        self.label_73.setObjectName("label_73")
        self.verticalLayout_60.addWidget(self.label_73)
        self.horizontalLayout_40 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_40.setSpacing(0)
        self.horizontalLayout_40.setObjectName("horizontalLayout_40")
        self.txtReportStartDate_4 = QtWidgets.QLineEdit(self.layoutWidget_10)
        self.txtReportStartDate_4.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("candara")
        font.setPointSize(11)
        self.txtReportStartDate_4.setFont(font)
        self.txtReportStartDate_4.setStyleSheet("background-color:#D9D9D9;\n"
"border:none;")
        self.txtReportStartDate_4.setText("")
        self.txtReportStartDate_4.setObjectName("txtReportStartDate_4")
        self.horizontalLayout_40.addWidget(self.txtReportStartDate_4)
        self.btnGetReportStartDate_4 = QtWidgets.QPushButton(self.layoutWidget_10)
        self.btnGetReportStartDate_4.setMinimumSize(QtCore.QSize(0, 30))
        self.btnGetReportStartDate_4.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setFamily("candara")
        font.setPointSize(10)
        self.btnGetReportStartDate_4.setFont(font)
        self.btnGetReportStartDate_4.setStyleSheet("QPushButton{\n"
"background-color:#2F8FEA;\n"
"border:none;\n"
"color: white;\n"
"text-align: center;\n"
"padding: 0px 15px;\n"
"border-radius:0;\n"
"\n"
"}\n"
"QPushButton:hover{\n"
"    background-color:#007DDA;\n"
"    background-color: #56648F;\n"
"    \n"
"}")
        self.btnGetReportStartDate_4.setObjectName("btnGetReportStartDate_4")
        self.horizontalLayout_40.addWidget(self.btnGetReportStartDate_4)
        self.verticalLayout_60.addLayout(self.horizontalLayout_40)
        self.layoutWidget_11 = QtWidgets.QWidget(self.frame_3)
        self.layoutWidget_11.setGeometry(QtCore.QRect(400, 20, 161, 59))
        self.layoutWidget_11.setObjectName("layoutWidget_11")
        self.verticalLayout_61 = QtWidgets.QVBoxLayout(self.layoutWidget_11)
        self.verticalLayout_61.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_61.setObjectName("verticalLayout_61")
        self.label_74 = QtWidgets.QLabel(self.layoutWidget_11)
        self.label_74.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("candara")
        font.setPointSize(10)
        self.label_74.setFont(font)
        self.label_74.setStyleSheet("color:#838383;")
        self.label_74.setObjectName("label_74")
        self.verticalLayout_61.addWidget(self.label_74)
        self.cmbReportRecordType_2 = QtWidgets.QComboBox(self.layoutWidget_11)
        self.cmbReportRecordType_2.setMinimumSize(QtCore.QSize(0, 30))
        self.cmbReportRecordType_2.setStyleSheet("border:none;\n"
"background-color:#D9D9D9;")
        self.cmbReportRecordType_2.setEditable(True)
        self.cmbReportRecordType_2.setObjectName("cmbReportRecordType_2")
        self.verticalLayout_61.addWidget(self.cmbReportRecordType_2)
        self.layoutWidget_12 = QtWidgets.QWidget(self.frame_3)
        self.layoutWidget_12.setGeometry(QtCore.QRect(570, 20, 181, 53))
        self.layoutWidget_12.setObjectName("layoutWidget_12")
        self.verticalLayout_29 = QtWidgets.QVBoxLayout(self.layoutWidget_12)
        self.verticalLayout_29.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_29.setObjectName("verticalLayout_29")
        self.label_36 = QtWidgets.QLabel(self.layoutWidget_12)
        self.label_36.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("candara")
        font.setPointSize(10)
        self.label_36.setFont(font)
        self.label_36.setStyleSheet("color:#838383;")
        self.label_36.setObjectName("label_36")
        self.verticalLayout_29.addWidget(self.label_36)
        self.txtIncomeRecordedBy_3 = QtWidgets.QLineEdit(self.layoutWidget_12)
        self.txtIncomeRecordedBy_3.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("candara")
        font.setPointSize(11)
        self.txtIncomeRecordedBy_3.setFont(font)
        self.txtIncomeRecordedBy_3.setStyleSheet("background-color:#D9D9D9;\n"
"border:none;")
        self.txtIncomeRecordedBy_3.setText("")
        self.txtIncomeRecordedBy_3.setObjectName("txtIncomeRecordedBy_3")
        self.verticalLayout_29.addWidget(self.txtIncomeRecordedBy_3)
        self.frame_4 = QtWidgets.QFrame(self.frame_3)
        self.frame_4.setGeometry(QtCore.QRect(20, 90, 151, 81))
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.btnGetCurrentStock_4 = QtWidgets.QPushButton(self.frame_4)
        self.btnGetCurrentStock_4.setGeometry(QtCore.QRect(10, 20, 121, 40))
        self.btnGetCurrentStock_4.setMinimumSize(QtCore.QSize(0, 40))
        self.btnGetCurrentStock_4.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setFamily("candara")
        font.setPointSize(10)
        self.btnGetCurrentStock_4.setFont(font)
        self.btnGetCurrentStock_4.setStyleSheet("QPushButton{\n"
"background-color:#487A85;\n"
"border:none;\n"
"color: white;\n"
"text-align: center;\n"
"padding: 0px 15px;\n"
"border-radius:10px;\n"
"\n"
"}\n"
"QPushButton:hover{\n"
"    background-color:#007DDA;\n"
"    background-color: #56648F;\n"
"    \n"
"}")
        self.btnGetCurrentStock_4.setObjectName("btnGetCurrentStock_4")
        self.tabWidget.addTab(self.tab_2, "")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Sistema de Registro"))
        self.label_69.setText(_translate("MainWindow", "Fecha Ingreso"))
        self.btnGetReportStartDate.setText(_translate("MainWindow", "..."))
        self.label_70.setText(_translate("MainWindow", "Fecha Egreso"))
        self.btnGetReportStartDate_2.setText(_translate("MainWindow", "..."))
        self.label_71.setText(_translate("MainWindow", "Tipo"))
        self.label_31.setText(_translate("MainWindow", "Número"))
        self.label_32.setText(_translate("MainWindow", "Título"))
        self.label_33.setText(_translate("MainWindow", "Observación"))
        self.label_34.setText(_translate("MainWindow", "Folio"))
        self.label_35.setText(_translate("MainWindow", "Destinatario"))
        self.btnGetCurrentStock.setText(_translate("MainWindow", "Insertar\n"
"nuevo"))
        self.btnGetCurrentStock_2.setText(_translate("MainWindow", "Actualizar\n"
"seleccionado"))
        self.btnGetCurrentStock_3.setText(_translate("MainWindow", "Eliminar\n"
"seleccionado"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab1), _translate("MainWindow", "Gestión de Registros"))
        self.label_72.setText(_translate("MainWindow", "Fecha Ingreso"))
        self.btnGetReportStartDate_3.setText(_translate("MainWindow", "..."))
        self.label_73.setText(_translate("MainWindow", "Fecha Egreso"))
        self.btnGetReportStartDate_4.setText(_translate("MainWindow", "..."))
        self.label_74.setText(_translate("MainWindow", "Tipo"))
        self.label_36.setText(_translate("MainWindow", "Número"))
        self.btnGetCurrentStock_4.setText(_translate("MainWindow", "Buscar"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Búsqueda"))
