# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1074, 865)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/system-logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("font-family:candara;\n"
"")
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setMinimumSize(QtCore.QSize(0, 50))
        self.frame_3.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.TopBar = QtWidgets.QWidget(self.frame_3)
        self.TopBar.setMinimumSize(QtCore.QSize(0, 50))
        self.TopBar.setMaximumSize(QtCore.QSize(16777215, 50))
        self.TopBar.setStyleSheet("QWidget{\n"
"border-bottom: 1px solid #B4B4B4;\n"
"background-color:white;\n"
"}\n"
"\n"
"")
        self.TopBar.setObjectName("TopBar")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.TopBar)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setSpacing(0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.frame_15 = QtWidgets.QFrame(self.TopBar)
        self.frame_15.setMaximumSize(QtCore.QSize(200, 16777215))
        self.frame_15.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_15.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_15.setObjectName("frame_15")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.frame_15)
        self.horizontalLayout_9.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout_9.setSpacing(15)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_10 = QtWidgets.QLabel(self.frame_15)
        font = QtGui.QFont()
        font.setFamily("candara")
        font.setPointSize(12)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("border:none;")
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_9.addWidget(self.label_10)
        self.horizontalLayout_8.addWidget(self.frame_15)
        self.frame_16 = QtWidgets.QFrame(self.TopBar)
        self.frame_16.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.frame_16.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_16.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_16.setObjectName("frame_16")
        self.horizontalLayout_8.addWidget(self.frame_16)
        self.frame_17 = QtWidgets.QFrame(self.TopBar)
        self.frame_17.setMaximumSize(QtCore.QSize(200, 16777215))
        self.frame_17.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_17.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_17.setObjectName("frame_17")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame_17)
        self.verticalLayout_7.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_7.setContentsMargins(0, 0, 15, 0)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_11 = QtWidgets.QLabel(self.frame_17)
        font = QtGui.QFont()
        font.setFamily("candara")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("border:none;")
        self.label_11.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_7.addWidget(self.label_11)
        self.lblSystemUsername = QtWidgets.QLabel(self.frame_17)
        font = QtGui.QFont()
        font.setFamily("candara")
        font.setPointSize(11)
        self.lblSystemUsername.setFont(font)
        self.lblSystemUsername.setStyleSheet("border:none;")
        self.lblSystemUsername.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblSystemUsername.setObjectName("lblSystemUsername")
        self.verticalLayout_7.addWidget(self.lblSystemUsername)
        self.horizontalLayout_8.addWidget(self.frame_17)
        self.horizontalLayout_2.addWidget(self.TopBar)
        self.verticalLayout.addWidget(self.frame_3)
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tabWidget = QtWidgets.QTabWidget(self.frame_2)
        self.tabWidget.setMaximumSize(QtCore.QSize(16777215, 250))
        self.tabWidget.setObjectName("tabWidget")
        self.tab1_2 = QtWidgets.QWidget()
        self.tab1_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.tab1_2.setObjectName("tab1_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.tab1_2)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.frame_11 = QtWidgets.QFrame(self.tab1_2)
        self.frame_11.setMaximumSize(QtCore.QSize(1200, 250))
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_11)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_62 = QtWidgets.QVBoxLayout()
        self.verticalLayout_62.setObjectName("verticalLayout_62")
        self.label_75 = QtWidgets.QLabel(self.frame_11)
        self.label_75.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("candara")
        font.setPointSize(10)
        self.label_75.setFont(font)
        self.label_75.setStyleSheet("color:#838383;")
        self.label_75.setObjectName("label_75")
        self.verticalLayout_62.addWidget(self.label_75)
        self.horizontalLayout_41 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_41.setSpacing(0)
        self.horizontalLayout_41.setObjectName("horizontalLayout_41")
        self.txtRecordStartDate = QtWidgets.QLineEdit(self.frame_11)
        self.txtRecordStartDate.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("candara")
        font.setPointSize(11)
        self.txtRecordStartDate.setFont(font)
        self.txtRecordStartDate.setStyleSheet("background-color:#D9D9D9;\n"
"border:none;")
        self.txtRecordStartDate.setText("")
        self.txtRecordStartDate.setReadOnly(True)
        self.txtRecordStartDate.setObjectName("txtRecordStartDate")
        self.horizontalLayout_41.addWidget(self.txtRecordStartDate)
        self.btnGetRecordStartDate = QtWidgets.QPushButton(self.frame_11)
        self.btnGetRecordStartDate.setMinimumSize(QtCore.QSize(0, 30))
        self.btnGetRecordStartDate.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setFamily("candara")
        font.setPointSize(10)
        self.btnGetRecordStartDate.setFont(font)
        self.btnGetRecordStartDate.setStyleSheet("QPushButton{\n"
"background-color:#2F8FEA;\n"
"border:none;\n"
"color: white;\n"
"text-align: center;\n"
"padding: 0px 15px;\n"
"border-radius:0;\n"
"\n"
"}\n"
"QPushButton:hover{\n"
"    background-color:#007DDA;\n"
"    background-color: #56648F;\n"
"    \n"
"}")
        self.btnGetRecordStartDate.setObjectName("btnGetRecordStartDate")
        self.horizontalLayout_41.addWidget(self.btnGetRecordStartDate)
        self.verticalLayout_62.addLayout(self.horizontalLayout_41)
        self.gridLayout.addLayout(self.verticalLayout_62, 0, 0, 1, 1)
        self.verticalLayout_63 = QtWidgets.QVBoxLayout()
        self.verticalLayout_63.setObjectName("verticalLayout_63")
        self.label_76 = QtWidgets.QLabel(self.frame_11)
        self.label_76.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("candara")
        font.setPointSize(10)
        self.label_76.setFont(font)
        self.label_76.setStyleSheet("color:#838383;")
        self.label_76.setObjectName("label_76")
        self.verticalLayout_63.addWidget(self.label_76)
        self.horizontalLayout_42 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_42.setSpacing(0)
        self.horizontalLayout_42.setObjectName("horizontalLayout_42")
        self.txtRecordEndDate = QtWidgets.QLineEdit(self.frame_11)
        self.txtRecordEndDate.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("candara")
        font.setPointSize(11)
        self.txtRecordEndDate.setFont(font)
        self.txtRecordEndDate.setStyleSheet("background-color:#D9D9D9;\n"
"border:none;")
        self.txtRecordEndDate.setText("")
        self.txtRecordEndDate.setReadOnly(True)
        self.txtRecordEndDate.setObjectName("txtRecordEndDate")
        self.horizontalLayout_42.addWidget(self.txtRecordEndDate)
        self.btnGetRecordEndDate = QtWidgets.QPushButton(self.frame_11)
        self.btnGetRecordEndDate.setMinimumSize(QtCore.QSize(0, 30))
        self.btnGetRecordEndDate.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setFamily("candara")
        font.setPointSize(10)
        self.btnGetRecordEndDate.setFont(font)
        self.btnGetRecordEndDate.setStyleSheet("QPushButton{\n"
"background-color:#2F8FEA;\n"
"border:none;\n"
"color: white;\n"
"text-align: center;\n"
"padding: 0px 15px;\n"
"border-radius:0;\n"
"\n"
"}\n"
"QPushButton:hover{\n"
"    background-color:#007DDA;\n"
"    background-color: #56648F;\n"
"    \n"
"}")
        self.btnGetRecordEndDate.setObjectName("btnGetRecordEndDate")
        self.horizontalLayout_42.addWidget(self.btnGetRecordEndDate)
        self.verticalLayout_63.addLayout(self.horizontalLayout_42)
        self.gridLayout.addLayout(self.verticalLayout_63, 0, 1, 1, 2)
        self.verticalLayout_64 = QtWidgets.QVBoxLayout()
        self.verticalLayout_64.setObjectName("verticalLayout_64")
        self.label_77 = QtWidgets.QLabel(self.frame_11)
        self.label_77.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("candara")
        font.setPointSize(10)
        self.label_77.setFont(font)
        self.label_77.setStyleSheet("color:#838383;")
        self.label_77.setObjectName("label_77")
        self.verticalLayout_64.addWidget(self.label_77)
        self.cmbRecordType = QtWidgets.QComboBox(self.frame_11)
        self.cmbRecordType.setMinimumSize(QtCore.QSize(0, 30))
        self.cmbRecordType.setStyleSheet("border:none;\n"
"background-color:#D9D9D9;")
        self.cmbRecordType.setEditable(False)
        self.cmbRecordType.setObjectName("cmbRecordType")
        self.verticalLayout_64.addWidget(self.cmbRecordType)
        self.gridLayout.addLayout(self.verticalLayout_64, 0, 3, 1, 1)
        self.verticalLayout_30 = QtWidgets.QVBoxLayout()
        self.verticalLayout_30.setObjectName("verticalLayout_30")
        self.label_37 = QtWidgets.QLabel(self.frame_11)
        self.label_37.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("candara")
        font.setPointSize(10)
        self.label_37.setFont(font)
        self.label_37.setStyleSheet("color:#838383;")
        self.label_37.setObjectName("label_37")
        self.verticalLayout_30.addWidget(self.label_37)
        self.txtRecordNumber = QtWidgets.QLineEdit(self.frame_11)
        self.txtRecordNumber.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("candara")
        font.setPointSize(11)
        self.txtRecordNumber.setFont(font)
        self.txtRecordNumber.setStyleSheet("background-color:#D9D9D9;\n"
"border:none;")
        self.txtRecordNumber.setText("")
        self.txtRecordNumber.setObjectName("txtRecordNumber")
        self.verticalLayout_30.addWidget(self.txtRecordNumber)
        self.gridLayout.addLayout(self.verticalLayout_30, 0, 4, 1, 1)
        self.verticalLayout_31 = QtWidgets.QVBoxLayout()
        self.verticalLayout_31.setObjectName("verticalLayout_31")
        self.label_38 = QtWidgets.QLabel(self.frame_11)
        self.label_38.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("candara")
        font.setPointSize(10)
        self.label_38.setFont(font)
        self.label_38.setStyleSheet("color:#838383;")
        self.label_38.setObjectName("label_38")
        self.verticalLayout_31.addWidget(self.label_38)
        self.txtRecordTitle = QtWidgets.QLineEdit(self.frame_11)
        self.txtRecordTitle.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("candara")
        font.setPointSize(11)
        self.txtRecordTitle.setFont(font)
        self.txtRecordTitle.setStyleSheet("background-color:#D9D9D9;\n"
"border:none;")
        self.txtRecordTitle.setText("")
        self.txtRecordTitle.setObjectName("txtRecordTitle")
        self.verticalLayout_31.addWidget(self.txtRecordTitle)
        self.gridLayout.addLayout(self.verticalLayout_31, 1, 0, 1, 1)
        self.verticalLayout_34 = QtWidgets.QVBoxLayout()
        self.verticalLayout_34.setObjectName("verticalLayout_34")
        self.label_41 = QtWidgets.QLabel(self.frame_11)
        self.label_41.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("candara")
        font.setPointSize(10)
        self.label_41.setFont(font)
        self.label_41.setStyleSheet("color:#838383;")
        self.label_41.setObjectName("label_41")
        self.verticalLayout_34.addWidget(self.label_41)
        self.txtRecordDestination = QtWidgets.QLineEdit(self.frame_11)
        self.txtRecordDestination.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("candara")
        font.setPointSize(11)
        self.txtRecordDestination.setFont(font)
        self.txtRecordDestination.setStyleSheet("background-color:#D9D9D9;\n"
"border:none;")
        self.txtRecordDestination.setText("")
        self.txtRecordDestination.setObjectName("txtRecordDestination")
        self.verticalLayout_34.addWidget(self.txtRecordDestination)
        self.gridLayout.addLayout(self.verticalLayout_34, 1, 1, 1, 1)
        self.verticalLayout_33 = QtWidgets.QVBoxLayout()
        self.verticalLayout_33.setObjectName("verticalLayout_33")
        self.label_40 = QtWidgets.QLabel(self.frame_11)
        self.label_40.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("candara")
        font.setPointSize(10)
        self.label_40.setFont(font)
        self.label_40.setStyleSheet("color:#838383;")
        self.label_40.setObjectName("label_40")
        self.verticalLayout_33.addWidget(self.label_40)
        self.txtRecordFolium = QtWidgets.QLineEdit(self.frame_11)
        self.txtRecordFolium.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("candara")
        font.setPointSize(11)
        self.txtRecordFolium.setFont(font)
        self.txtRecordFolium.setStyleSheet("background-color:#D9D9D9;\n"
"border:none;")
        self.txtRecordFolium.setText("")
        self.txtRecordFolium.setObjectName("txtRecordFolium")
        self.verticalLayout_33.addWidget(self.txtRecordFolium)
        self.gridLayout.addLayout(self.verticalLayout_33, 1, 3, 1, 1)
        self.frame_12 = QtWidgets.QFrame(self.frame_11)
        self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.btnRecordInsert = QtWidgets.QPushButton(self.frame_12)
        self.btnRecordInsert.setGeometry(QtCore.QRect(10, 40, 110, 40))
        self.btnRecordInsert.setMinimumSize(QtCore.QSize(110, 40))
        self.btnRecordInsert.setMaximumSize(QtCore.QSize(110, 16777215))
        font = QtGui.QFont()
        font.setFamily("candara")
        font.setPointSize(10)
        self.btnRecordInsert.setFont(font)
        self.btnRecordInsert.setStyleSheet("QPushButton{\n"
"background-color:#487A85;\n"
"border:none;\n"
"color: white;\n"
"text-align: center;\n"
"padding: 0px 15px;\n"
"border-radius:10px;\n"
"\n"
"}\n"
"QPushButton:hover{\n"
"    background-color:#007DDA;\n"
"    background-color: #56648F;\n"
"    \n"
"}")
        self.btnRecordInsert.setObjectName("btnRecordInsert")
        self.btnRecordUpdate = QtWidgets.QPushButton(self.frame_12)
        self.btnRecordUpdate.setGeometry(QtCore.QRect(140, 40, 110, 40))
        self.btnRecordUpdate.setMinimumSize(QtCore.QSize(110, 40))
        self.btnRecordUpdate.setMaximumSize(QtCore.QSize(110, 16777215))
        font = QtGui.QFont()
        font.setFamily("candara")
        font.setPointSize(10)
        self.btnRecordUpdate.setFont(font)
        self.btnRecordUpdate.setStyleSheet("QPushButton{\n"
"background-color:#4A4A4A;\n"
"border:none;\n"
"color: white;\n"
"text-align: center;\n"
"padding: 0px 15px;\n"
"border-radius:10px;\n"
"\n"
"}\n"
"QPushButton:hover{\n"
"    background-color:#007DDA;\n"
"    background-color: #56648F;\n"
"    \n"
"}")
        self.btnRecordUpdate.setObjectName("btnRecordUpdate")
        self.btnRecordDelete = QtWidgets.QPushButton(self.frame_12)
        self.btnRecordDelete.setGeometry(QtCore.QRect(270, 40, 110, 40))
        self.btnRecordDelete.setMinimumSize(QtCore.QSize(110, 40))
        self.btnRecordDelete.setMaximumSize(QtCore.QSize(110, 16777215))
        font = QtGui.QFont()
        font.setFamily("candara")
        font.setPointSize(10)
        self.btnRecordDelete.setFont(font)
        self.btnRecordDelete.setStyleSheet("QPushButton{\n"
"background-color:#88435D;\n"
"border:none;\n"
"color: white;\n"
"text-align: center;\n"
"padding: 0px 15px;\n"
"border-radius:10px;\n"
"\n"
"}\n"
"QPushButton:hover{\n"
"    background-color:#007DDA;\n"
"    background-color: #56648F;\n"
"    \n"
"}")
        self.btnRecordDelete.setObjectName("btnRecordDelete")
        self.btnRecordExport = QtWidgets.QPushButton(self.frame_12)
        self.btnRecordExport.setGeometry(QtCore.QRect(400, 40, 110, 40))
        self.btnRecordExport.setMinimumSize(QtCore.QSize(110, 40))
        self.btnRecordExport.setMaximumSize(QtCore.QSize(110, 16777215))
        font = QtGui.QFont()
        font.setFamily("candara")
        font.setPointSize(10)
        self.btnRecordExport.setFont(font)
        self.btnRecordExport.setStyleSheet("QPushButton{\n"
"background-color:#B57E25;\n"
"border:none;\n"
"color: white;\n"
"text-align: center;\n"
"padding: 0px 15px;\n"
"border-radius:10px;\n"
"\n"
"}\n"
"QPushButton:hover{\n"
"    background-color:#007DDA;\n"
"    background-color: #56648F;\n"
"    \n"
"}")
        self.btnRecordExport.setObjectName("btnRecordExport")
        self.gridLayout.addWidget(self.frame_12, 2, 2, 1, 3)
        self.verticalLayout_32 = QtWidgets.QVBoxLayout()
        self.verticalLayout_32.setObjectName("verticalLayout_32")
        self.label_39 = QtWidgets.QLabel(self.frame_11)
        self.label_39.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("candara")
        font.setPointSize(10)
        self.label_39.setFont(font)
        self.label_39.setStyleSheet("color:#838383;")
        self.label_39.setObjectName("label_39")
        self.verticalLayout_32.addWidget(self.label_39)
        self.txtRecordObservation = QtWidgets.QTextEdit(self.frame_11)
        self.txtRecordObservation.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.txtRecordObservation.setStyleSheet("background-color:#D9D9D9;\n"
"border:none;")
        self.txtRecordObservation.setObjectName("txtRecordObservation")
        self.verticalLayout_32.addWidget(self.txtRecordObservation)
        self.gridLayout.addLayout(self.verticalLayout_32, 2, 0, 1, 2)
        self.horizontalLayout_3.addWidget(self.frame_11)
        self.tabWidget.addTab(self.tab1_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.tab_3)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.frame_13 = QtWidgets.QFrame(self.tab_3)
        self.frame_13.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame_13.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_13)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.frame_14 = QtWidgets.QFrame(self.frame_13)
        self.frame_14.setMaximumSize(QtCore.QSize(800, 16777215))
        self.frame_14.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_14.setObjectName("frame_14")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_14)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout_65 = QtWidgets.QVBoxLayout()
        self.verticalLayout_65.setObjectName("verticalLayout_65")
        self.label_78 = QtWidgets.QLabel(self.frame_14)
        self.label_78.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("candara")
        font.setPointSize(10)
        self.label_78.setFont(font)
        self.label_78.setStyleSheet("color:#838383;")
        self.label_78.setObjectName("label_78")
        self.verticalLayout_65.addWidget(self.label_78)
        self.horizontalLayout_43 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_43.setSpacing(0)
        self.horizontalLayout_43.setObjectName("horizontalLayout_43")
        self.txtSearchRecordStartDate = QtWidgets.QLineEdit(self.frame_14)
        self.txtSearchRecordStartDate.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("candara")
        font.setPointSize(11)
        self.txtSearchRecordStartDate.setFont(font)
        self.txtSearchRecordStartDate.setStyleSheet("background-color:#D9D9D9;\n"
"border:none;")
        self.txtSearchRecordStartDate.setText("")
        self.txtSearchRecordStartDate.setReadOnly(True)
        self.txtSearchRecordStartDate.setObjectName("txtSearchRecordStartDate")
        self.horizontalLayout_43.addWidget(self.txtSearchRecordStartDate)
        self.btnGetSearchStartDate = QtWidgets.QPushButton(self.frame_14)
        self.btnGetSearchStartDate.setMinimumSize(QtCore.QSize(0, 30))
        self.btnGetSearchStartDate.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setFamily("candara")
        font.setPointSize(10)
        self.btnGetSearchStartDate.setFont(font)
        self.btnGetSearchStartDate.setStyleSheet("QPushButton{\n"
"background-color:#2F8FEA;\n"
"border:none;\n"
"color: white;\n"
"text-align: center;\n"
"padding: 0px 15px;\n"
"border-radius:0;\n"
"\n"
"}\n"
"QPushButton:hover{\n"
"    background-color:#007DDA;\n"
"    background-color: #56648F;\n"
"    \n"
"}")
        self.btnGetSearchStartDate.setObjectName("btnGetSearchStartDate")
        self.horizontalLayout_43.addWidget(self.btnGetSearchStartDate)
        self.verticalLayout_65.addLayout(self.horizontalLayout_43)
        self.gridLayout_2.addLayout(self.verticalLayout_65, 0, 0, 1, 1)
        self.verticalLayout_66 = QtWidgets.QVBoxLayout()
        self.verticalLayout_66.setObjectName("verticalLayout_66")
        self.label_79 = QtWidgets.QLabel(self.frame_14)
        self.label_79.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("candara")
        font.setPointSize(10)
        self.label_79.setFont(font)
        self.label_79.setStyleSheet("color:#838383;")
        self.label_79.setObjectName("label_79")
        self.verticalLayout_66.addWidget(self.label_79)
        self.horizontalLayout_44 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_44.setSpacing(0)
        self.horizontalLayout_44.setObjectName("horizontalLayout_44")
        self.txtSearchRecordEndDate = QtWidgets.QLineEdit(self.frame_14)
        self.txtSearchRecordEndDate.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("candara")
        font.setPointSize(11)
        self.txtSearchRecordEndDate.setFont(font)
        self.txtSearchRecordEndDate.setStyleSheet("background-color:#D9D9D9;\n"
"border:none;")
        self.txtSearchRecordEndDate.setText("")
        self.txtSearchRecordEndDate.setReadOnly(True)
        self.txtSearchRecordEndDate.setObjectName("txtSearchRecordEndDate")
        self.horizontalLayout_44.addWidget(self.txtSearchRecordEndDate)
        self.btnGetSearchEndDate = QtWidgets.QPushButton(self.frame_14)
        self.btnGetSearchEndDate.setMinimumSize(QtCore.QSize(0, 30))
        self.btnGetSearchEndDate.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setFamily("candara")
        font.setPointSize(10)
        self.btnGetSearchEndDate.setFont(font)
        self.btnGetSearchEndDate.setStyleSheet("QPushButton{\n"
"background-color:#2F8FEA;\n"
"border:none;\n"
"color: white;\n"
"text-align: center;\n"
"padding: 0px 15px;\n"
"border-radius:0;\n"
"\n"
"}\n"
"QPushButton:hover{\n"
"    background-color:#007DDA;\n"
"    background-color: #56648F;\n"
"    \n"
"}")
        self.btnGetSearchEndDate.setObjectName("btnGetSearchEndDate")
        self.horizontalLayout_44.addWidget(self.btnGetSearchEndDate)
        self.verticalLayout_66.addLayout(self.horizontalLayout_44)
        self.gridLayout_2.addLayout(self.verticalLayout_66, 0, 1, 1, 1)
        self.verticalLayout_67 = QtWidgets.QVBoxLayout()
        self.verticalLayout_67.setObjectName("verticalLayout_67")
        self.label_80 = QtWidgets.QLabel(self.frame_14)
        self.label_80.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("candara")
        font.setPointSize(10)
        self.label_80.setFont(font)
        self.label_80.setStyleSheet("color:#838383;")
        self.label_80.setObjectName("label_80")
        self.verticalLayout_67.addWidget(self.label_80)
        self.cmbSearchRecordType = QtWidgets.QComboBox(self.frame_14)
        self.cmbSearchRecordType.setMinimumSize(QtCore.QSize(160, 30))
        self.cmbSearchRecordType.setStyleSheet("border:none;\n"
"background-color:#D9D9D9;")
        self.cmbSearchRecordType.setEditable(True)
        self.cmbSearchRecordType.setObjectName("cmbSearchRecordType")
        self.verticalLayout_67.addWidget(self.cmbSearchRecordType)
        self.gridLayout_2.addLayout(self.verticalLayout_67, 0, 2, 1, 1)
        self.verticalLayout_35 = QtWidgets.QVBoxLayout()
        self.verticalLayout_35.setObjectName("verticalLayout_35")
        self.label_42 = QtWidgets.QLabel(self.frame_14)
        self.label_42.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("candara")
        font.setPointSize(10)
        self.label_42.setFont(font)
        self.label_42.setStyleSheet("color:#838383;")
        self.label_42.setObjectName("label_42")
        self.verticalLayout_35.addWidget(self.label_42)
        self.txtSearchRecordNumber = QtWidgets.QLineEdit(self.frame_14)
        self.txtSearchRecordNumber.setMinimumSize(QtCore.QSize(160, 30))
        font = QtGui.QFont()
        font.setFamily("candara")
        font.setPointSize(11)
        self.txtSearchRecordNumber.setFont(font)
        self.txtSearchRecordNumber.setStyleSheet("background-color:#D9D9D9;\n"
"border:none;")
        self.txtSearchRecordNumber.setText("")
        self.txtSearchRecordNumber.setObjectName("txtSearchRecordNumber")
        self.verticalLayout_35.addWidget(self.txtSearchRecordNumber)
        self.gridLayout_2.addLayout(self.verticalLayout_35, 0, 3, 1, 1)
        self.frame_18 = QtWidgets.QFrame(self.frame_14)
        self.frame_18.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_18.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_18.setObjectName("frame_18")
        self.btnSearchRecords = QtWidgets.QPushButton(self.frame_18)
        self.btnSearchRecords.setGeometry(QtCore.QRect(0, 20, 121, 40))
        self.btnSearchRecords.setMinimumSize(QtCore.QSize(0, 40))
        self.btnSearchRecords.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setFamily("candara")
        font.setPointSize(10)
        self.btnSearchRecords.setFont(font)
        self.btnSearchRecords.setStyleSheet("QPushButton{\n"
"background-color:#487A85;\n"
"border:none;\n"
"color: white;\n"
"text-align: center;\n"
"padding: 0px 15px;\n"
"border-radius:10px;\n"
"\n"
"}\n"
"QPushButton:hover{\n"
"    background-color:#007DDA;\n"
"    background-color: #56648F;\n"
"    \n"
"}")
        self.btnSearchRecords.setObjectName("btnSearchRecords")
        self.btnClearSearchRecords = QtWidgets.QPushButton(self.frame_18)
        self.btnClearSearchRecords.setGeometry(QtCore.QRect(130, 20, 121, 40))
        self.btnClearSearchRecords.setMinimumSize(QtCore.QSize(0, 40))
        self.btnClearSearchRecords.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setFamily("candara")
        font.setPointSize(10)
        self.btnClearSearchRecords.setFont(font)
        self.btnClearSearchRecords.setStyleSheet("QPushButton{\n"
"background-color:#B57E25;\n"
"border:none;\n"
"color: white;\n"
"text-align: center;\n"
"padding: 0px 15px;\n"
"border-radius:10px;\n"
"\n"
"}\n"
"QPushButton:hover{\n"
"    background-color:#007DDA;\n"
"    background-color: #56648F;\n"
"    \n"
"}")
        self.btnClearSearchRecords.setObjectName("btnClearSearchRecords")
        self.gridLayout_2.addWidget(self.frame_18, 1, 0, 1, 2)
        self.horizontalLayout_5.addWidget(self.frame_14)
        self.horizontalLayout_4.addWidget(self.frame_13)
        self.tabWidget.addTab(self.tab_3, "")
        self.verticalLayout_2.addWidget(self.tabWidget)
        self.tableViewRecords = QtWidgets.QTableView(self.frame_2)
        self.tableViewRecords.setMinimumSize(QtCore.QSize(0, 450))
        self.tableViewRecords.setStyleSheet("border:none;\n"
"")
        self.tableViewRecords.setGridStyle(QtCore.Qt.SolidLine)
        self.tableViewRecords.setObjectName("tableViewRecords")
        self.verticalLayout_2.addWidget(self.tableViewRecords)
        self.verticalLayout.addWidget(self.frame_2)
        self.horizontalLayout.addWidget(self.frame)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Sistema de Registro"))
        self.label_10.setText(_translate("MainWindow", "Sistema de registros"))
        self.label_11.setText(_translate("MainWindow", "Bienvenido"))
        self.lblSystemUsername.setText(_translate("MainWindow", "Username"))
        self.label_75.setText(_translate("MainWindow", "Fecha Ingreso"))
        self.btnGetRecordStartDate.setText(_translate("MainWindow", "..."))
        self.label_76.setText(_translate("MainWindow", "Fecha Egreso"))
        self.btnGetRecordEndDate.setText(_translate("MainWindow", "..."))
        self.label_77.setText(_translate("MainWindow", "Tipo"))
        self.label_37.setText(_translate("MainWindow", "Número"))
        self.label_38.setText(_translate("MainWindow", "Título"))
        self.label_41.setText(_translate("MainWindow", "Destinatario"))
        self.label_40.setText(_translate("MainWindow", "Folio"))
        self.btnRecordInsert.setText(_translate("MainWindow", "Insertar\n"
"nuevo"))
        self.btnRecordUpdate.setText(_translate("MainWindow", "Actualizar\n"
"seleccionado"))
        self.btnRecordDelete.setText(_translate("MainWindow", "Eliminar\n"
"seleccionado"))
        self.btnRecordExport.setText(_translate("MainWindow", "Exportar"))
        self.label_39.setText(_translate("MainWindow", "Observación"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab1_2), _translate("MainWindow", "Gestión de Registros"))
        self.label_78.setText(_translate("MainWindow", "Fecha Ingreso"))
        self.btnGetSearchStartDate.setText(_translate("MainWindow", "..."))
        self.label_79.setText(_translate("MainWindow", "Fecha Egreso"))
        self.btnGetSearchEndDate.setText(_translate("MainWindow", "..."))
        self.label_80.setText(_translate("MainWindow", "Tipo"))
        self.label_42.setText(_translate("MainWindow", "Número"))
        self.btnSearchRecords.setText(_translate("MainWindow", "Buscar"))
        self.btnClearSearchRecords.setText(_translate("MainWindow", "Limpiar campos"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Búsqueda"))
